"""Constants for the Tapo S200B/S200D integration."""

from homeassistant.const import Platform

DOMAIN = "tapo_s200b"
PLATFORMS = (
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
    Platform.EVENT,
    Platform.SENSOR,
)

CONF_EMAIL = "email"
CONF_MAC = "mac"
CONF_POLL_INTERVAL = "poll_interval"
CONF_PAGE_SIZE = "page_size"

DEFAULT_POLL_INTERVAL = 1.0
MIN_POLL_INTERVAL = 0.5
MAX_POLL_INTERVAL = 10.0
DEFAULT_PAGE_SIZE = 50
DIAGNOSTIC_POLL_INTERVAL = 60
MIN_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100
MAX_PAGES_PER_POLL = 10
DISCOVERY_CACHE_SECONDS = 30.0
DISCOVERY_TIMEOUT_SECONDS = 3
SUPPORTED_HUB_MODELS = frozenset({"H110", "H110C"})
SUPPORTED_BUTTON_MODELS = frozenset({"S200B", "S200D"})

DIAGNOSTIC_CLOUD_CONNECTION = "cloud_connection"
DIAGNOSTIC_SIGNAL_LEVEL = "signal_level"
DIAGNOSTIC_BATTERY_LOW = "battery_low"
DIAGNOSTIC_RSSI = "rssi"
DIAGNOSTIC_REBOOT = "reboot"
DIAGNOSTIC_UNPAIR = "unpair"
DIAGNOSTIC_FEATURES = frozenset({
    DIAGNOSTIC_CLOUD_CONNECTION,
    DIAGNOSTIC_SIGNAL_LEVEL,
    DIAGNOSTIC_BATTERY_LOW,
    DIAGNOSTIC_RSSI,
    DIAGNOSTIC_REBOOT,
    DIAGNOSTIC_UNPAIR,
})

STORE_VERSION = 1

EVENT_SINGLE_CLICK = "single_click"
EVENT_DOUBLE_CLICK = "double_click"
EVENT_ROTATE_RIGHT = "rotate_right"
EVENT_ROTATE_LEFT = "rotate_left"
EVENT_TYPES = (
    EVENT_SINGLE_CLICK,
    EVENT_DOUBLE_CLICK,
    EVENT_ROTATE_RIGHT,
    EVENT_ROTATE_LEFT,
)

ROTATION_STEP_DEGREES = 30
MAX_ROTATION_DEGREES = 720
MAX_ROTATION_STEPS = MAX_ROTATION_DEGREES // ROTATION_STEP_DEGREES
MAX_EMISSIONS_PER_POLL = 64
RECENT_EVENT_IDS_LIMIT = 512
